### ISSUE TITLE
Document different models, policies and their uses

### ISSUE THREAD

**Issue by dankolbman** [overture-stack/ego#118]
The resources that ego exposes are not defined anywhere and causes some confusion for exactly what each should be used for. Each model and resource should be documented with it's intended use and any implications that may arise from it's properties.
Some sample questions that may come from the developer that would be nice to have answered in the documentation are:

### User
- How are users created? (various login providers?)
- What is the `status` property? Is there a user lifecycle?

### Group
- Is there any significance to groups beyond user segregation?

### Application
- What is an application? Is it a login provider or does it allow ego to be an oauth provider?
- What is the relation between an application and a group?
- What is the relation between an application and a user?

### Auth
- What is the public key auth type? Does ego generate its own user keys?

**Comment by alekspejovic** [comment]
Addressed in documentation.
