### ISSUE TITLE
Get Group Permissions fails if the group has a permission set.

### ISSUE THREAD

**Issue by KevinFHartmann** [overture-stack/ego#144]
"timestamp": "2018-08-27T14:25:43.464+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Type definition error: [simple type, class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.overture.ego.model.dto.PageDTO[\"resultSet\"]->java.util.Collections$UnmodifiableRandomAccessList[0]->org.overture.ego.model.entity.AclGroupPermission[\"entity\"]->org.overture.ego.model.entity.AclEntity_$$_jvst9c2_3[\"handler\"])",
  "path": "/groups/4f872545-4b13-450c-8235-b51fdbbac399/permissions"
}

**Comment by KevinFHartmann** [comment]
Fixed in current release.

**Comment by petertogara** [comment]
fdghjkghjk
