### ISSUE TITLE
Need better error handling for redundant scopes

### ISSUE THREAD

**Issue by KevinFHartmann** [overture-stack/ego#183]
IssueToken throws an exception if you try to issue a token with a scope that already exists (eg. song.WRITE, song.READ ) triggers 
the following exception:

org.springframework.dao.DataIntegrityViolationException: A different object with the same identifier value was already associated with the session : [bio.overture.ego.model.entity.TokenScope#song.READ]; nested exception is javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [bio.overture.ego.model.entity.TokenScope#song.READ]] with root cause
javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [bio.overture.ego.model.entity.TokenScope#song.READ]

- [ ] Unit test
- [ ] Implementation

**Comment by KevinFHartmann** [comment]
We'll revisit this once Alex and Rob are done dispelling some of the Hibernate magic...

**Comment by rosibaj** [comment]
should be handled by #308 - Closing as the specs are updated in that ticket
