### ISSUE TITLE
Decouple DTOs from DAOs

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#228]
many `create` methods in service use the DAO as a DTO and commit to the database, which is misleading. In userservice, the create method does the following:
1. `user.setName(user.getEmail())`
2. `user.setCreatedAt(new Date())`
3. hibernate automatically generates the Id for the entity, meaning the user does not have control over it

When the web client sends the `User` payload for the create endpoint, the webclient might have populated the `id` field thinking the id can be defined by the webclient, when really hibernate randomly generates it. Like wise with the name and createdAt field.

One solution is to sanitize the `User` payload for id, createdAt and name and throw exceptions indicating incorrect usage or conflicts.

The better solution, would be to create a `CreateUserRequest` DTO that is a simple Pojo with no hibernate related annotations. When the `CreateUserRequest` is sent to the `UserService.create` method, the method will ensure the DAO is properly created using the input request, and then save to the database. 

The create method is one of many places, another could be the update method. For instance
`PUT /users/update/myUserId-12345` with payload `UserUpdateRequest` where `UserUpdateRequest` would contain a subset of the `User` DAO fields that are allowed to be updated (for instance you cannot update the `createdAt` field as that is defined at creation time) 

This is an epic because every service needs to be modified and this could break alot of things

**Comment by rtisma** [comment]
Depends on #229

**Comment by andricDu** [comment]
not priotity
