### ISSUE TITLE
Implement application client credentials flow 

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/ego#234]
We need to implement a flow so that applications can access resources, outside the context of a user.

Currently, the authorization for most of Ego's endpoints accepts a Bearer JWT, and checks to see whether the user is an admin. Only users who are admins are authorized to operate on Ego's resources. 

We need to create an 'Application JWT' as well. This JWT should contain information on the application's 'role' (describes it's privileges).  

A new request method should be added to the auth controller which follows this design - https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/. (Application makes request passing in client id and secret via Basic auth & grant_type=client_credentials , retrieves Application JWT in the response). 

The application then passes this JWT in the authorization header when calling on Ego's endpoints. If the application is 'privileged', it is able to operate on the resources ( in the same way that an admin can). 

TO DO:

- [ ] Add a role field to Application table , assign values to indicate privilege
- [ ] Create Application JWT
- [ ] Create new method in auth controller (pass in client id and secret and get back application JWT)
- [ ] Accept Application JWT as authorization for other methods (check whether application is privileged)

**Comment by dankolbman** [comment]
How is this different from the JWT issued from the existing client credentials flow?
Will application roles be shared with the user roles?

We've been interested in accessing deeper ego data via application tokens (they can only be verified by ego at the moment, no api access), so we're looking forward to this 👍

**Comment by andricDu** [comment]
@dankolbman currently there is no way to differentiate an application from a `client` application and a `system` or `administrative` application.

We are planning on adding that distinction.

**Comment by Fgerthoffert** [comment]
Rename role column to type
