### ISSUE TITLE
Create Application testplan

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#289]
Create a spreadsheet planning the test cases we are interested in

- adding/deleting groups from applications
- adding/deleting users from applications
- adding/deleting tokens from applications
- updating application data
- checks (invalid UUIDS, identical requests, malformed requests, illegal requests)
- ensuring deletion does not cascade unexpectedtly

**Comment by rosibaj** [comment]
@rtisma I think this is done - can you confirm?
