### ISSUE TITLE
Name is blank when user registers with Ego using gmail

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/ego#300]
![Screen Shot 2019-03-11 at 11 29 39 AM](https://user-images.githubusercontent.com/12387683/54137072-55f8e680-43f3-11e9-9b0d-248f863fa0d5.png)

**Comment by alekspejovic** [comment]
![](https://files.slack.com/files-pri/T033B0H01-FGVU1TGBH/screen_shot_2019-03-11_at_11.29.39_am.png)

**Comment by rosibaj** [comment]
this is a config issue when ego is set-up - instance is resolved.
