### ISSUE TITLE
Existing tokens should be revoked when DENY is applied

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/ego#301]
- [ ] If a user has existing tokens for a scope, and we  apply the DENY access level for the same policy, those tokens  should be revoked (set isRevoked = True).

- [ ] On the token manager ui, any token that is Revoked should `not` show in the active token list 
- [ ] The deny scope _should_ show in the scope list, but the checkbox should be disabled and the user should NOT be able to generate a token from a deny scope

**Comment by rosibaj** [comment]
@andricDu (@alekspejovic) Behaviour has been confirmed with Christina and details updated in this ticket.  Lmk if any questions
