### ISSUE TITLE
Group Permissions not showing in `GET /users/{id}/permissions`

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#303]
Endpoint for: /users/{userid}/scopes

![image](https://user-images.githubusercontent.com/15824252/54307123-40292400-45a1-11e9-979d-2028b341ff7c.png)

**Comment by andricDu** [comment]
The current behaviour is correct. Permissions are directly assigned to either users or groups. They are not inherited. Scopes are inherited (the effective value of the merged permissions).

What we really need is an endpoint to just retrieve the inherited scopes.

**Comment by rosibaj** [comment]
👍 @andricDu I will add that as a task/ticket that can be done with the ego ui update coming soon.
