### ISSUE TITLE
Change expiry from 1000 days to 365 for tokens (api keys)

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/ego#312]
- Expiry is being stored as the issue date and then expiry is based off of that 
- In case of breach,  you could make invalid tokens valid by manipulating config
- Ensure the expiry date is a column in the table so that the configuration cannot change previously expired tokens 
- The length of token expiry should be a config set by the Ego Admin

**Comment by andricDu** [comment]
https://github.com/overture-stack/ego/pull/321
