### ISSUE TITLE
GRPC Methods for Ego

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#345]
GRPC is a protocol to communicate.  We want to implement a GRPC framework to improve EGO performance.  Implement Ego GRPC Methods for:

- [ ] Read Users (WIP) - Jon
- [ ] Write users
- [ ] Read Group
- [ ] Write Group
- [ ] Read Policies
- [ ] Write Policies
- [ ] Assign Permissions
- [ ] Filter by permission

**Comment by andricDu** [comment]
gRPC would improve performance marginally, as in it would eliminate the tiny HTTP overhead for each request. Once we have a need for ego to stream millions of users, groups, and applications per request, then we can revisit this.

Our effort is much better spent in optimizing queries, adding intelligent caching, and cleaning up code.
