### ISSUE TITLE
AccessToken scopes not updated when policy name is update

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#361]
# Problem
When the name of a policy is changed, the scopes assigned to an access token are not updated to reflect that change. Changing the name of a policy can invalidate tokens. Since the token scopes are meant to be immutable, and a policy name was changed, then the check_token endpoint should indicate one of the scopes associated with the token does not exist (which will be a clue to a policy name change) and the user should delete the token and generate a new one.

# Replication
1. create a user, policy (name=something-123) and userpermission with `WRITE` assigned to the user for policy `something-123`
2. generate a token with the scope `something-123.WRITE`
3. verify `something-123.WRITE` is output when calling check_token endpoint with that token
4. update the policy name from `something-123` to `robocop-456`
5. call the check_token endpoint for the same access token, and the output will incorrectly show `something-123.WRITE` as a scope instead of the expected `robocop-456.WRITE` scope.

**Comment by alekspejovic** [comment]
Not an issue - this works.
