### ISSUE TITLE
BUG - AssertJ causing long compile times

### ISSUE THREAD

**Issue by andricDu** [overture-stack/ego#376]
AssertJ was identified as causing long test compile times. 

## Description
Currently AssertJ has been the cause of long compile times for the tests. I removed a lot of it from our existing code and it alleviated the issue a lot. We should make the effort to remove it from the rest of the tests. 

## Expected Behaviour
`mvn test-compile` should not take a long time

## Actual Behaviour
`mvn test-compile` takes longer than it should 

## Possible Fix
replace `AssertJ.assertThat` calls with just the basic `Junit.assertEquals` and the like. 

## Steps to Reproduce
Run `mvn test-compile`

## Your Environment
JDK11 Mac and Linux

**Comment by jaserud** [comment]
This has been resolved in #377
