### ISSUE TITLE
Feature Request: Token Refresh

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#379]
## Detailed Description

Currently, ego has no support for token refresh.  JWTs should last a limited amount of time (30 minutes ex), while  refresh tokens lasting 24 hours.

Providing a refresh token allows a user to stay navigated within a site, without having to login constantly.  Short-lived JWTs assure that access is restricted and verified often.

**Comment by andricDu** [comment]
The success criteria for ego should be as described above while following the OAuth2.0 spec on refresh tokens: https://tools.ietf.org/html/rfc6749#section-1.5

**Comment by Buwujiu** [comment]
## Possible Implementation
1. Modify existing endpoint `GET  / oauth / ego-token` to return access token + refresh token,
https://github.com/overture-stack/ego/blob/develop/src/main/java/bio/overture/ego/controller/AuthController.java#L127

2. Create a new endpoint in ego to take a refresh token and return a new access token.

3. Question: Where to store the refresh token? 
One solution is to store the refresh token in secured Https-only cookies: 
refer to 5. Put the Refresh Token in a Cookie in
https://www.baeldung.com/spring-security-oauth2-refresh-token-angular-js

**Comment by andricDu** [comment]
The problem with HTTP only cookies, is that if we are using them, they will be sent with all requests to the issuing domain, opening us up to CSRF style vulnerabilities unless we implement additional CSRF token protection. 

LocalStorage is protected by same origin policy but isn't automatically sent with all requests.

**Comment by rosibaj** [comment]
@Buwujiu Can you record this on the wiki so we can keep comments there for review? 
 https://wiki.oicr.on.ca/display/icgcargotech/Refresh+Token+specs
