### ISSUE TITLE
Add scope to application JWT

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/ego#393]
Ego needs to issue application jwt in order to support service communication, for example, `ClinicalService.READ` should be issued when SONG requires resources from clinical submission. 

This is needed to support song/clinical integration for argo.

**Comment by rosibaj** [comment]
Discussion in planning - the clinical system should accept application-level JWTs instead. 

The correct clinical endpoints should use the application level endpoints.

**Comment by rosibaj** [comment]
discussion to be schedule with @joneubank @rtisma @Buwujiu

**Comment by andricDu** [comment]
Applications do not get assigned permissions on policies

**Comment by rosibaj** [comment]
Closing this as the correct methodology was determined in planning meeting
