### ISSUE TITLE
Implement Refresh Token in Ego

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/ego#394]
Wiki Specs: 
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=DCCSOFT&title=Fall+2019%3A+Ego+Updates+to+manage+Permissions#Fall2019:EgoUpdatestomanagePermissions-3.1.3TechnicalImplementationSpecs

## Exit Criteria
- [ ] it works

**Comment by anncatton** [comment]
Created a feature branch pr for this ticket: https://github.com/overture-stack/ego/pull/432
