### ISSUE TITLE
Domain for ego

### ISSUE THREAD

**Issue by andricDu** [overture-stack/ego#4]

**Comment by andricDu** [comment]
Don't believe I have permissions and domain has not been settled.

**Comment by andricDu** [comment]
Not exactly a domain for ego specifically, but we did get this: elastic ip drp.kfdrc.org

**Comment by allisonheath** [comment]
So what functionality will go under this (sub)domain? 

I think we'll try to gather all of those and get together a better naming scheme. Production domain name TBD, but we have kfdrc.org for now for development purposes.

**Comment by andricDu** [comment]
I think ideally what I was hoping was something like `*.portal.<kids_first>.org` where all our services powering the data resource portal would go as subdomains to the drp just so we can be explicit in the scope of the services.

`drp.kfdrc.org` should be more than enough for us now, and maybe we don't need further subdomains and can just reverse proxy services.

Basically we just wanted a name for our sandbox so we wouldn't step on anyone's toes.
