### ISSUE TITLE
Update AppTokenClaim to contain scopes 

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#400]
In order to authorized an application as a client, the applications token must contain scopes, to allow downstream services to authorize it.

## Detailed Description

Will need to add a "scope" section to AppTokenContext object, and populate using ApplicationService with scopes associated with a particular application.

This is specifically important for song, which will need to use argo-clinical's id api. argo-clinical requires CLINICALSERVICE.READ scope, which mean, the JWT that song sends in its request must contain that scope to be authorized

**Comment by rosibaj** [comment]
Application to Application communication has a JWT that is used; no explicit scoped need to be assigned.  Application to Application communication is considered secure.
