### ISSUE TITLE
Ego Authentication doesn't verify the client secret for applications

### ISSUE THREAD

**Issue by KevinFHartmann** [overture-stack/ego#402]
%genAuthToken program-service meow
Bearer cHJvZ3JhbS1zZXJ2aWNlOm1lb3c=
This token works, but it shouldn't.

**Comment by KevinFHartmann** [comment]
@ApplicationScoped annotation also doesn't work... Fixing it...

**Comment by rosibaj** [comment]
@andricDu to deplpy into ARGO QA
