### ISSUE TITLE
Update token to api-key

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#408]
https://wiki.oicr.on.ca/display/DCCSOFT/Fall+2019%3A+Ego+Updates+to+manage+Permissions#Fall2019:EgoUpdatestomanagePermissions-3.2TokenControllerUpdates

Currently user API key is generated using the token controller endpoints.  However, Ego also issues JWT (JSON Web Token).  It has become confusing to reference 2 separate features by the same "token name".  

Rename all token-controller endpoints to API-key
No functionality should change in the endpoints - just the terminology needs to change.

**Comment by andricDu** [comment]
@rosibaj https://ego.qa.overture.bio/api/swagger-ui.html

**Comment by rosibaj** [comment]
@andricDu 👍 ive started testing - no issues so far so should close today. want to make sure i make followup tickets before closing!
