### ISSUE TITLE
Redirect URI in Ego

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#418]
Depending on the sign-in location, you may wish to send users to different locations in your application.  For example, some differing situations that we have encountered in ARGO:

- Logging in to the homepage should direct you passed on returned information 
- Logging in from the join user flow should direct you to the rest of the join program 
- Logging in from a saved url should redirect you to that url 

Currently, Ego only has the ability to redirect to a single URL unless you log multiple applications.  We would like the ability to have multiple redirect URIs.

**Comment by rosibaj** [comment]
@andricDu Whats the tag with this release?  I want to comment it in the ui update ticket for argo

**Comment by andricDu** [comment]
@rosibaj 2.9.1
