### ISSUE TITLE
BUG - Missing json content type for several Swagger ui endpoints

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#466]
# Problem 
Currently, the Content-Type `application/json` is missing on several requests on the swagger doc

For example these endpoints:
/swagger-ui.html#!/group-controller/getUsersForGroupUsingGET
/swagger-ui.html#!/group-controller/getGroupPermissionsForGroupUsingGET

# Solutions:
1. Update swagger and see
Its possible that spring-fox has fixed several issues, and that there is better resolution of what the Content-Type would be even without a definition. For instance, song has a more up to date spring-fox version and it does not explicitly define the content type on its controllers however its swagger ui properlly includes it. This could be a quick fix if this is the case. Also, this should happen anyway

2. If the previous step does not fix the issue, then possibly update ALL annotations with the right content type on the controllers
Something like this (this could be a by product of an older version of spring fox)
https://github.com/overture-stack/SONG/blob/develop/song-server/src/main/java/bio/overture/song/server/controller/SubmitController.java#L51-L53

3. Verify that the content is not missing on any additional endpoints

**Comment by rosibaj** [comment]
version deployed in prod argo environment
