### ISSUE TITLE
Create a permission on an application

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#468]
Add the ability for an application to be associated to a policy/mask in a similar manner to the user 

- [ ] Add a new join table similar to userPermissions and groupPermissions as  reference
- [ ]  Flyway migration
- [ ] Add the unit tests for this feature

## Test results
https://docs.google.com/document/d/1xs3HJgj1qHtDZ63p2wQ8mF_V9zom8JFB27rwV0eIoTo/edit?ts=5f526d62

**Comment by gokul472** [comment]
This ticket blocks the following tickets:
469/470/471

**Comment by rosibaj** [comment]
Tested September 04 - tested Add permission for an application 
Goal: Use the addpermission endpoint to successfully add a new permission 

- ListPermissions is working as expected; was able to see all assigned permissions directly 
- AddPermissions is working as expected - permissions are updated if changing mask, and permissions for different policies can be added to the same application.  Saw the count on list permissions update correctly after using Add Permissions

**Comment by gokul472** [comment]
This ticket can now be closed.
Test results are attached here.
https://docs.google.com/document/d/1xs3HJgj1qHtDZ63p2wQ8mF_V9zom8JFB27rwV0eIoTo/edit?ts=5f526d62
