### ISSUE TITLE
Reflect the application scopes in the JWT

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#470]
Create application JWT object

Follow the JWT spec:
https://wiki.oicr.on.ca/display/OV/JWT+Specification

Outcome:

- [ ] When you execute the curl command and decode the JWT, you should see the scope and the application information.

- [ ] Calling the endpoint will get the correct output values.

- [ ] Expose application JWT creation endpoint in Swagger.
https://github.com/overture-stack/ego/blob/develop/src/main/java/bio/overture/ego/config/SwaggerConfig.java#L69

## Test results:
https://docs.google.com/document/d/1xs3HJgj1qHtDZ63p2wQ8mF_V9zom8JFB27rwV0eIoTo/edit?ts=5f526d62

**Comment by gokul472** [comment]
As per discussion with @anncatton , moving this ticket to Sprint 3

**Comment by rosibaj** [comment]
Tested from September 04 - Test the scopes in the application JWT 
https://ego.qa.overture.bio//api/swagger-ui.html#/Auth/postAccessTokenUsingPOST

Was able to generate a application JWT 
- The JWT had the `application` object as expected. This section listed the application details. 
- Tested adding different permissions and watching them resolve in the JWT.  If deny is added via groups, the resolve permission was working correctly and DENY was listed in the JWT.

**Comment by gokul472** [comment]
@b-f-chan - this ticket can now be closed.
