### ISSUE TITLE
Update policyController with Application Permissions

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#471]
Add to the policyController the ability to associate applications ( mirroring the User and Group endpoints)

## Test Results
https://docs.google.com/document/d/1xs3HJgj1qHtDZ63p2wQ8mF_V9zom8JFB27rwV0eIoTo/edit?ts=5f526d62

**Comment by gokul472** [comment]
@b-f-chan :
3 scenarios have been tested:
1) Get all the application for a specific policy
2) Adding the policies for the application 
3) Deleting the policy for the application.
Feel free to review the results..

https://docs.google.com/document/d/1xs3HJgj1qHtDZ63p2wQ8mF_V9zom8JFB27rwV0eIoTo/edit?ts=5f526d62

**Comment by b-f-chan** [comment]
Testing will be done in Sprint 6

**Comment by b-f-chan** [comment]
Done, closing
