### ISSUE TITLE
Update user and application jwts to contain explicit scopes

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#493]
Currently, a mega apikey and user jwt does not have the exact same list of scopes. The same applies with application jwts

For instance, if the user has score.WRITE and song.READ

The api key would have: `score.WRITE`, `score.READ`, `song.READ`
The user jwt would have: `score.WRITE`, `song.READ`

This means, for JWTs, the client needs to be aware of EGOs presedence rules and implement logic to process this. This means clients are dependent on EGOs rules, making them unusable with other OAuth2 authorization servers that don't necessarily follow these rules.

Adding explicit scopes will be backwards compatible, meaning client software will not need to be updated.

**Comment by rosibaj** [comment]
@rtisma since you are working on this i went ahead and added it to the current sprint

**Comment by rosibaj** [comment]
edit - pr is WIP to keep idea.  misunderstood

**Comment by gokul472** [comment]
This ticket will ensure that the all the clients (including SONG and SCORE), it matches against the list of scopes with EGO.
For EGO: Write -> both read and Write ops
Read: only read ops
Deny - no read and no write ops

**Comment by b-f-chan** [comment]
Will carryover to Sprint 6, testing to be done there

**Comment by b-f-chan** [comment]
Will carryover & complete testing at start of Sprint 7, deploy to staging came later in sprint, then priority on final GDC release kept me from getting to this.

**Comment by rosibaj** [comment]
@b-f-chan was testing completed on this?

**Comment by b-f-chan** [comment]
Application Explicit Scopes - Testing on Staging:

- Successfully created test app & policy via EGO UI
- Successfully assigned policy.WRITE permission to app via Swagger endpoint (/applications/{id}/permissions)
- Successfully verified resolved permissions on app by querying Swagger endpoint (/applications/{id}/groups/permissions)
- Successfully verified explicit scopes (policy.WRITE, policy.READ) appear in application JWT via Swagger endpoint (/oauth/token
postAccessToken)
- Successfully verified same explicit scopes appear when decoded using jwt.io

User Explicit Scopes - Testing on Staging:

- To be completed ...
