### ISSUE TITLE
Update EGO to Handle Chrome SameSite Cookie Changes

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego#500]
Update EGO to handle the new way Chrome is using SameSite cookies

**Comment by anncatton** [comment]
Timeline from chrome: https://www.chromium.org/updates/same-site
A little more discussion: [Duo article](https://duo.com/decipher/google-rolls-out-samesite-cookie-changes-to-chrome#:~:text=The%20SameSite%20update%20changes%20how,(CSRF)%20attempts%20using%20cookies.&text=%E2%80%9C%23SameSite%20cookie%20update%20now%20at,Twitter%20account%20Chrome%20Developers%20posted.)

Spec is [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)

This behaviour is supposed to come to Firefox eventually too

**Comment by hlminh2000** [comment]
Chrome's change means that for authenticating applications that are hosted on a different domain from Ego,  the browser will not send the cookie set by Ego on the authenticating application upon redirect, which means it cannot retrieve the JWT after completing the login flow.

This affects any application that is hosted on a different domain from Ego. For Argo, this includes `localhost` for local development, and RDPC UI

**Comment by rosibaj** [comment]
Confirmed - can login to RDPC UI from Chrome now!
