### ISSUE TITLE
BUG - Application Token returns 403 when it should be 500

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#506]
## Steps to Reproduce
- In Argo QA env, format request below with kship-rdpc application details
https://ego.qa.argo.cancercollaboratory.org/api/swagger-ui.html#/Auth/postAccessTokenUsingPOST

 curl -X POST "https://ego.qa.argo.cancercollaboratory.org/api/oauth/token?client_id=<id here pls>&client_secret=<id here pls>=client_credentials" -H "accept: application/json"

- See the Repsonse
![image](https://user-images.githubusercontent.com/15824252/95388150-beee5c00-08bf-11eb-9401-b1d4eaba24ba.png)

- [x] Include  default scope `*.deny` 
- [ ] Add validation to not allow special characters in policy name `?.\/&[]()`.  If a policy is tried ot be named with one of these throw an error showing all charactrs not allowed 
## Expected Behaviour
- the request should not return a 400; the request IS formatted correctly with valid parameters
- the request should return a 200 code with an AccessToken included with  `scopes: ["*.deny" ]`

**Comment by b-f-chan** [comment]
Canarie team won't be able to take this up in Sprint 8 (both devs out for 1 week each) along with the existing sprint content

Agreed with @rosibaj will have to shift back to ARGO team!

**Comment by anncatton** [comment]
We were throwing the 403 here before Spring took over: https://github.com/overture-stack/ego/blob/develop/src/main/java/bio/overture/ego/service/ApplicationService.java#L264

**Comment by rosibaj** [comment]
@joneubank is this tagged for testing somewhere i can verify before i let platform team know they can go ahead?

**Comment by rosibaj** [comment]
Tested this on Overture QA environment: 
![image](https://user-images.githubusercontent.com/15824252/98702096-009f7600-2348-11eb-837b-773278b73da7.png)

**Comment by joneubank** [comment]
As written in expected behaviour.
