### ISSUE TITLE
Remove aud claims from JWTs returned from /oauth/token

### ISSUE THREAD

**Issue by jaserud** [overture-stack/ego#513]
The JWT returned under the client credentials flow has `aud` claims which seems to be set to the name of the application in ego's database.

## Detailed Description
- JWT returned under the client credentials flow has `aud` claims 
- this claim is set to the name of the application in ego's database
- the claim is optional and complicates implementation in other services if we want to follow it [spec](https://tools.ietf.org/html/rfc7519#page-9) because we have to check that the correct app exists in the aud claim

```
{
  "iat": 1603911215,
  "exp": 1603911515,
  "iss": "ego",
  "aud": [
    "oauth2-resource"
  ],
  "context": {
    "scope": [...],
    "application": {
      "name": "oauth2-resource",
      "clientId": "oauth",
      "status": "APPROVED",
      "type": "CLIENT"
    }
  }
}

```
## Possible Implementation
- remove "aud" calims

**Comment by rosibaj** [comment]
tested on Overture QA Environment: 
![image](https://user-images.githubusercontent.com/15824252/98701876-c0d88e80-2347-11eb-8405-aed6e2689042.png)

@jaserud lgtm!
