### ISSUE TITLE
Enhance EGO User Documentation

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego#514]
Review, add extra content & details to EGO user docs.  Existing docs for Admin, App Developers:
https://ego.readthedocs.io/en/latest/index.html

**Comment by rosibaj** [comment]
blocked by: https://github.com/overture-stack/ego/issues/556

**Comment by b-f-chan** [comment]
Unblocked, install & config instructions provided

**Comment by b-f-chan** [comment]
Reviewed, updated, released to prod.  Closing.
