### ISSUE TITLE
Rename `providerId` to `providerSubjectId`

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#534]
During the #507 PR review, feedback was to rename **providerId** to **providerSubjectId**.   **providerId** may be confused with being a unique ID for the Provider itself, which it is not.  Rather, these are the definitions agreed on for providerType, providerSubjectId, and e-mail in the idToken received from the Provider:

**idToken.providerType** = Specific identity provider supplying the incoming ID Token (e.g. GOOGLE, GITHUB, LINKEDIN, etc.).
**idToken.providerSubjectId** - Identifier that the provider has assigned to the user who is the subject of the token
**idToken.email** = E-mail address associated with the user who is the subject of the token

**Comment by b-f-chan** [comment]
Tested in QA, API response shows field renamed correctly to "providerSubjectId", for example:

`{"id":"7bc4ee24-aae1-4d8d-b50f-f8a6dd1ff3e8","email":"Brandon.Chan@oicr.on.ca","status":"APPROVED","firstName":"","lastName":"","createdAt":"2021-02-10T12:44:26.292+0000","lastLogin":"2021-02-10T12:44:26.296+0000","preferredLanguage":null,"providerType":"GITHUB","providerSubjectId":"40768946","type":"USER"}`
