### ISSUE TITLE
Change User Name Update & Parsing Logic

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego#561]
To support the bug fix in ego-ui#125 (see that ticket for details), these changes also need to be made to EGO core itself:

- Set First Name, Last Name from the provider token only on initial user create; do not update on subsequent logins
- Update name parsing logic as follows:
    - Split string by whitespace
    - Put last element as Last Name
    - Everything else goes into First Name
    - Assumption: If only one name is provided, it will be stored in First Name

**Comment by anncatton** [comment]
In pr review, @andricDu pointed out that the update user endpoint should be a `PATCH`, not a `PUT`. I'm adding this to the code changes here.
- This is a breaking change, the fix for ego-ui will be included in [ego-ui-125](https://github.com/overture-stack/ego-ui/issues/125)

**Comment by b-f-chan** [comment]
Tested successfully in staging, name population now behaves as described above
