### ISSUE TITLE
Review Ego 3.7 Vulnerabilities from `Dependency-Check`

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego#566]
Review the Ego 3.7 vulnerabilities from `Dependency-Check` to see which are real and fixable

Focus on CRITICAL, HIGH - Will arrange fixes only after analysis done

Attached:
[https://app.zenhub.com/files/106007715/643df0fa-c085-4cba-aa56-369a6ad1f3ae/download](https://app.zenhub.com/files/106007715/643df0fa-c085-4cba-aa56-369a6ad1f3ae/download)

**Comment by anncatton** [comment]
https://docs.google.com/spreadsheets/d/1TDJCg-JXyawr1WZH6NhgwkLbaXNj-j99T6kkgh-fj2k/edit#gid=0

**Comment by akachru-github** [comment]
@b-f-chan , @anncatton , is this the the right state for this ticket?

**Comment by anncatton** [comment]
A lot of this is going to be outdated now that bashar is doing all that ego work, so not even sure this ticket is relevant anymore?

**Comment by akachru-github** [comment]
If not relevant, will close.
