### ISSUE TITLE
Feature Request: Fix deprecated spring-security-oauth2 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#571]
https://stackoverflow.com/questions/59273338/what-is-the-replacement-for-the-deprecated-authorizationserver-in-spring-securit
https://spring.io/projects/spring-security-oauth

> As announced on the Spring blog (https://spring.io/projects/spring-security-oauth)

To that end, the plan is to provide patch and security fixes for the Spring Security Oauth 2.4.x and 2.5.x line until May 2021. Additionally, security fixes will be supported for the 2.5.x line until May 2022, at which point the project will have reached end-of-life.

https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide

**Comment by akachru-github** [comment]
We are currently on we’re on spring-security-oauth2 2.0.17.RELEASE. Next steps are to immediately upgrade to 2.5.x to tap into the next years worth of support.

**Comment by rosibaj** [comment]
@blabadi is this ticket in progress now?

**Comment by blabadi** [comment]
This ticket is now done
4.5.0 was deployed in overture-qa & staging and tested by Brandon
3.6.1 was deployed and tested in ARGO environments up to prod yesterday by Rosi.
