### ISSUE TITLE
New OAuth2 Client libraries (5.1.0)

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/ego#613]
- update Spring security 5.5.x
  - Spring security oauth2 starter
- switch ego to use the new oauth2 client configs (see: OAuth2 Client related changes)
  - Refactor OAuth2Sso filter and oauth2 login
    - request resolver
    - update secure server config
  - Update ego oauth2 providers config
    - update ego redirect urls in each provider
  - Use custom oauth2 users and user info service
    - create custom logic to handle non standard providers
  - test login with providers
- fix / update tests
- release and test (overture qa)

**Comment by blabadi** [comment]
this has been deployed and tested on overture staging, changes documented in the same wiki of the epic
