### ISSUE TITLE
Test Ego 5.0.0 in Overture QA

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/ego#619]
- This will be our first formal testing of Ego in the Overture environment to respect a new process of releasing Overture components independently of other consuming projects. 
- This ticket will include documenting the necessary sanity and integration tests that are required to check that the new version of Ego is operating as expected. Once complete, Ego 5.0.0 can be merged and made available for other consuming projects to upgrade to.

**Comment by blabadi** [comment]
tbd: 

Ego test cases:

- Infrastructure:
	- ego starts
	- no error in logs
	- vault secrets loaded correctly
	- correct spring profiles
	- ego jwt public key is correct
	
- Login 
	- login with google
	- login with orcid
	- login with github
	- keycloak login
	- login create user with correct information 
	
- CRUD
	- edit user: change fields, disable/enable, type etc
	- create / edit / delete a: group, policy, application
	- add / remove user from: group, policy, application
	- add / remove group from: policy / application
	
- tokens
	- generate api token https://dms-ui.qa.overture.bio/user
	- revoke api token
	- get app client jwt (rest api)
		- check scopes
		- check application info
	- get user jwt
		- verify scopes, groups, user info
		- verify token format

- integrations (when applicable):
	- song / score download
