### ISSUE TITLE
Add prompt=select_account to Google Auth URLs

### ISSUE THREAD

**Issue by samrichca** [overture-stack/ego#645]
- Add `?prompt=select_account` URL param for Google login.
- The goal is to show the account selection screen every time a user logs in or joins a program.
- Currently, if the user is logged into Chrome or Gmail, that session will be used automatically.
- Addresses https://github.com/icgc-argo/platform-ui/issues/2215 but may affect other Ego clients.

**Comment by b-f-chan** [comment]
Whoever gets to it first, assign to Bashar for now

**Comment by blabadi** [comment]
done in configurations in vault for ARGO, no coding needed. will close as won't do
