### ISSUE TITLE
Create a PassportBrokerRegistry

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/ego#699]
## Detailed Description
Create a PassportBrokerRegistry service that holds the list of passports from config. 
Initialize PassportBrokerRegistry from config. 
## Exit Criteria
On app startup, the passportBrokers reads from application.yaml and add to registry.

**Comment by leoraba** [comment]
Closing ticket, no need to create a PassportBrokerRegistry as Passport broker details are hold by a spring security class `ClientRegistrationRepository`
