### ISSUE TITLE
user pagination not working

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#70]
- go to users
- select page 1 on pagination at bottom
- select page 3 on pagination at bottom.  the users are not shifted according to the pagination.  Are there really 11 pages of users?  
- Add a user count ( 1-10 of 75 users) to let people know how many users there are 

![screen shot 2018-01-03 at 1 38 02 pm](https://user-images.githubusercontent.com/15824252/34534242-71c4e6aa-f08b-11e7-9935-e604a4cd4c5e.png)
![screen shot 2018-01-03 at 1 38 14 pm](https://user-images.githubusercontent.com/15824252/34534243-71d1b024-f08b-11e7-9636-2366f27a7891.png)

**Comment by Jephuff** [comment]
The API is currently returning the same results regardless of offset.
